apiVersion: apps/v1
kind: Deployment
metadata:
  name: drpoc-deploy
  labels:
    app: drpoc-app
spec:
  selector:
    matchLabels:
      app: drpoc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: drpoc-app
    spec:
      containers:
      - name: helloworld-app-container
        image: "quay.io/fxiang1/helloworld:0.0.1"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3002
        env:
          - name: "PORT"
            value: "3002"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          request:
            cpu: 50m
            memory: 64Mi