apiVersion: v1
kind: Service
metadata:
  name: drpoc-svc
  labels:
    app: drpoc-app
spec:
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: drpoc-app